# Generated by Django 4.2 on 2025-12-14 15:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='farm',
            name='administrative_region',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='governorate',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='farms/'),
        ),
        migrations.AddField(
            model_name='farm',
            name='image_url',
            field=models.TextField(blank=True, default='https://www.alyaum.com/uploads/images/2021/07/05/thumbs/350x350/1097681.jpg', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='price_per_kg',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='السعر/كجم', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='farm',
            name='type',
            field=models.CharField(blank=True, choices=[('dates', 'تمور'), ('dairy', 'ألبان'), ('vegetables', 'خضروات'), ('fruits', 'فواكه')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.TextField(blank=True, default='https://www.alyaum.com/uploads/images/2021/07/05/thumbs/350x350/1097681.jpg', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='location',
            field=models.URLField(max_length=500),
        ),
    ]
