# Generated by Django 4.2 on 2025-12-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_farm_created_at_remove_farm_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='price_per_kg',
            field=models.CharField(blank=True, help_text='السعر/كجم (مثل: 78 ريال/كجم)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='type',
            field=models.CharField(blank=True, choices=[('تمور', 'تمور'), ('ألبان', 'ألبان'), ('خضروات', 'خضروات'), ('فواكه', 'فواكه')], max_length=100, null=True),
        ),
    ]
