# Generated by Django 4.2 on 2025-12-14 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_farm_price_per_kg_alter_farm_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='daily_capacity',
            field=models.IntegerField(blank=True, default=0, help_text='Maximum number of orders per day', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
