# Generated by Django 4.2 on 2026-01-13 16:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_order_delivery_address_order_delivery_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="daily_order_limit",
            field=models.IntegerField(
                default=5,
                help_text="Maximum number of orders per day for this user",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
