# Generated by Django 4.2 on 2026-01-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_user_daily_order_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="tracking_number",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
